name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: npm install

      - name: Test
        run: npm test
